projects:
  schema:
    schema: 'http://localhost:4000/graphql'
    documents: ''
    extensions:
      codegen:
        generates:
          ./schema.graphql:
            plugins:
              - schema-ast
  enums:
    schema: 'schema.graphql'
    documents: ''
    extensions:
      codegen:
        generates:
          src/domains/enums/__generated__/enums.ts:
            plugins:
              - typescript
            config:
              enumsAsTypes: true
              onlyOperationTypes: true
